// mockData.js
const chefMockData = [
    {
      id: 1,
      name: 'Chef John',
      cuisine: 'Nyama Choma',
      availability: 'lunch',
      servings: 4,
      cookTime: '1 hour',
      rating: 4,
      location: 'Nairobi',
      profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/chef2.jpg',
      cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringMenu1.png'
    },
    {
      id: 2,
      name: 'Chef Doe',
      cuisine: 'Ugali and Fish',
      availability: 'lunch',
      servings: 2,
      cookTime: '45 minutes',
      rating: 4,
      location: 'Nairobi',
      profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF1.jpg',
      cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/ugalifish.png',
    },
    {
      id: 3,
      name: 'Chef Michael',
      cuisine: 'Sukuma Wiki',
      availability: 'lunch',
      servings: 6,
      cookTime: '30 minutes',
      rating: 3,
      location: 'Nairobi',
      profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF2.jpg',
      cuisineImage:'https://chefconnectapp.s3.ap-south-1.amazonaws.com/sukuma.png',
    },
    {
        id: 4,
        name: 'Chef Rafael',
        cuisine: 'Nyama Choma',
        availability: 'lunch',
        servings: 5,
        cookTime: '1 hour',
        rating: 5,
        location: 'Nakuru',
        profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/chef2.jpg',
        cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringMenu1.png'
      },
      {
        id: 5,
        name: 'Chef Ali',
        cuisine: 'Ugali and Fish',
        availability: 'lunch',
        servings: 5,
        cookTime: '45 minutes',
        rating: 5,
        location: 'Nakuru',
        profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF1.jpg',
        cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/ugalifish.png',
      },
      {
        id: 6,
        name: 'Chef Mike',
        cuisine: 'Sukuma Wiki',
        availability: 'lunch',
        servings: 4,
        cookTime: '30 minutes',
        rating: 4,
        location: 'Nakuru',
        profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF2.jpg',
        cuisineImage:'https://chefconnectapp.s3.ap-south-1.amazonaws.com/sukuma.png',
      },
      {
        id: 7,
        name: 'Chef Ahmed',
        cuisine: 'Nyama Choma',
        availability: 'lunch',
        servings: 5,
        cookTime: '1 hour',
        rating: 5,
        location: 'Mombasa',
        profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/chef2.jpg',
        cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringMenu1.png'
      },
      {
        id: 8,
        name: 'Chef Mohammed',
        cuisine: 'Ugali and Fish',
        availability: 'lunch',
        servings: 3,
        cookTime: '45 minutes',
        rating: 5,
        location: 'Mombasa',
        profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF1.jpg',
        cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/ugalifish.png',
      },
      {
        id: 9,
        name: 'Chef Husein',
        cuisine: 'Sukuma Wiki',
        availability: 'lunch',
        servings: 5,
        cookTime: '30 minutes',
        rating: 4,
        location: 'Mombasa',
        profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF2.jpg',
        cuisineImage:'https://chefconnectapp.s3.ap-south-1.amazonaws.com/sukuma.png',
      },
      {
        id: 10,
        name: 'Chef Henry',
        cuisine: 'Nyama Choma',
        availability: 'dinner',
        servings: 5,
        cookTime: '1 hour',
        rating: 5,
        location: 'Nairobi',
        profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/chef2.jpg',
        cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringMenu1.png'
      },
      {
        id: 11,
        name: 'Chef William',
        cuisine: 'Ugali and Fish',
        availability: 'dinner',
        servings: 4,
        cookTime: '50 minutes',
        rating: 4,
        location: 'Nairobi',
        profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF1.jpg',
        cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/ugalifish.png',
      },
      {
        id: 12,
        name: 'Chef Charles',
        cuisine: 'Sukuma Wiki',
        availability: 'dinner',
        servings: 7,
        cookTime: '40 minutes',
        rating: 3,
        location: 'Nairobi',
        profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF2.jpg',
        cuisineImage:'https://chefconnectapp.s3.ap-south-1.amazonaws.com/sukuma.png',
      },
      {
          id: 13,
          name: 'Chef Liam',
          cuisine: 'Nyama Choma',
          availability: 'dinner',
          servings: 4,
          cookTime: '1 hour',
          rating: 5,
          location: 'Nakuru',
          profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/chef2.jpg',
          cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringMenu1.png'
        },
        {
          id: 14,
          name: 'Chef Lucas',
          cuisine: 'Ugali and Fish',
          availability: 'dinner',
          servings: 2,
          cookTime: '40 minutes',
          rating: 5,
          location: 'Nakuru',
          profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF1.jpg',
          cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/ugalifish.png',
        },
        {
          id: 15,
          name: 'Chef Leo',
          cuisine: 'Sukuma Wiki',
          availability: 'dinner',
          servings: 5,
          cookTime: '30 minutes',
          rating: 4,
          location: 'Nakuru',
          profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF2.jpg',
          cuisineImage:'https://chefconnectapp.s3.ap-south-1.amazonaws.com/sukuma.png',
        },
        {
          id: 16,
          name: 'Chef Abdallah',
          cuisine: 'Nyama Choma',
          servings: 5,
          cookTime: '1 hour',
          availability: 'dinner',
          rating: 5,
          location: 'Mombasa',
          profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/chef2.jpg',
          cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringMenu1.png'
        },
        {
          id: 17,
          name: 'Chef Malik',
          cuisine: 'Ugali and Fish',
          availability: 'dinner',
          servings: 3,
          cookTime: '45 minutes',
          rating: 4,
          location: 'Mombasa',
          profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF1.jpg',
          cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/ugalifish.png',
        },
        {
          id: 18,
          name: 'Chef Arman',
          cuisine: 'Sukuma Wiki',
          availability: 'dinner',
          servings: 7,
          cookTime: '30 minutes',
          rating: 4,
          location: 'Mombasa',
          profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF2.jpg',
          cuisineImage:'https://chefconnectapp.s3.ap-south-1.amazonaws.com/sukuma.png',
        },
        {
            id: 19,
            name: 'Chef Ethan',
            cuisine: 'Nyama Choma',
            servings: 8,
            cookTime: '1 hour',
            availability: 'Weekend',
            rating: 4,
            location: 'Nairobi',
            profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/chef2.jpg',
            cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringMenu1.png'
          },
          {
            id: 20,
            name: 'Chef Oliver',
            cuisine: 'Ugali and Fish',
            availability: 'Weekend',
            servings: 5,
            cookTime: '55 minutes',
            rating: 4,
            location: 'Nairobi',
            profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF1.jpg',
            cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/ugalifish.png',
          },
          {
            id: 21,
            name: 'Chef Joe',
            cuisine: 'Sukuma Wiki',
            availability: 'Weekend',
            servings: 4,
            cookTime: '25 minutes',
            rating: 3,
            location: 'Nairobi',
            profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF2.jpg',
            cuisineImage:'https://chefconnectapp.s3.ap-south-1.amazonaws.com/sukuma.png',
          },
          {
              id: 22,
              name: 'Chef Noah',
              cuisine: 'Nyama Choma',
              servings: 5,
              cookTime: '1 hour',
              availability: 'weekend',
              rating: 5,
              location: 'Nakuru',
              profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/chef2.jpg',
              cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringMenu1.png'
            },
            {
              id: 23,
              name: 'Chef Elijah',
              cuisine: 'Ugali and Fish',
              servings: 3,
              cookTime: '55 minutes',
              availability: 'weekend',
              rating: 5,
              location: 'Nakuru',
              profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF1.jpg',
              cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/ugalifish.png',
            },
            {
              id: 24,
              name: 'Chef Alexander',
              cuisine: 'Sukuma Wiki',
              availability: 'weekend',
              servings: 5,
              cookTime: '40 minutes',
              rating: 4,
              location: 'Nakuru',
              profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF2.jpg',
              cuisineImage:'https://chefconnectapp.s3.ap-south-1.amazonaws.com/sukuma.png',
            },
            {
              id: 25,
              name: 'Chef Farhan',
              cuisine: 'Nyama Choma',
              servings: 6,
              cookTime: '1 hour',
              availability: 'weekends',
              rating: 5,
              location: 'Mombasa',
              profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/chef2.jpg',
              cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringMenu1.png'
            },
            {
              id: 26,
              name: 'Chef Ahsan',
              cuisine: 'Ugali and Fish',
              availability: 'weekends',
              servings: 4,
              cookTime: '50 minutes',
              rating: 5,
              location: 'Mombasa',
              profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF1.jpg',
              cuisineImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/ugalifish.png',
            },
            {
              id: 27,
              name: 'Chef Akeem',
              cuisine: 'Sukuma Wiki',
              availability: 'weekends',
              servings: 6,
              cookTime: '35 minutes',
              rating: 4,
              location: 'Mombasa',
              profileImage: 'https://chefconnectapp.s3.ap-south-1.amazonaws.com/CateringF2.jpg',
              cuisineImage:'https://chefconnectapp.s3.ap-south-1.amazonaws.com/sukuma.png',
            },
    
  ];
  
  export default chefMockData;
  